services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    networks:
      - backend
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: interview123

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: interview123
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db-vol:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: backend_api
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/backend
    #   - /usr/src/backend/node_modules
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: interview123
      DB_NAME: interview
    depends_on:
      - mysql

  frontend:
    container_name: next_frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  backend:

volumes:
  db-vol:
